server:
  port: 8080
  servlet:
    context-path:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: flag
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/miyuan
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
